packages:
  - packages/*
allowBuilds:
  "@shopify/react-native-skia": true
  better-sqlite3: true
  esbuild: true
allowUnusedPatches: true
catalog:
  "@expo/metro-runtime": 55.0.11
  "@sentry/react-native": 8.9.2
  babel-preset-expo: 55.0.6
  expo: 55.0.6
  expo-audio: 55.0.6
  expo-blur: ~55.0.9
  expo-calendar: ~55.0.7
  expo-camera: ~55.0.18
  expo-contacts: ~55.0.14
  expo-file-system: ~55.0.17
  expo-haptics: ~55.0.14
  expo-image: ~55.0.11
  expo-image-picker: ~55.0.19
  expo-linear-gradient: ~55.0.8
  expo-media-library: ~55.0.15
  expo-notifications: ~55.0.12
  expo-router: 55.0.5
  expo-video: 55.0.5
  nativewind: ^4.2.3
  oxlint: ^1.60.0
  react: 19.2.0
  react-dom: 19.2.0
  react-native: 0.83.2
  react-native-css-interop: ^0.2.3
  react-native-reanimated: 4.2.1
  react-native-web: ~0.21.0
  typescript: ~5.9.2
lockfileIncludeTarballUrl: false
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - miaoda-expo-devkit
onlyBuiltDependencies:
  - "@shopify/react-native-skia"
  - better-sqlite3
  - esbuild
overrides:
  expo-audio: 55.0.6
  expo-video: 55.0.5
  metro-core: 0.83.7
packageExtensions:
  react-native-gifted-charts:
    dependencies:
      expo-linear-gradient: ~55.0.8
patchedDependencies:
  "@shopify/react-native-skia@2.4.18": patches/@shopify__react-native-skia@2.4.18.patch
  expo@55.0.6: patches/expo@55.0.6.patch
publicHoistPattern:
  - "@babel/*"
  - "@expo/config-plugins"
