name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # حدثنا نسخة نود كمان عشان pnpm

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # بنسطب الأداة السحرية pnpm 🚀

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: pnpm # بنخليه يتعامل مع pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile # التثبيت السريع والذكي اللي هيحل المشكلة 😎

      - name: Build Android Preview (APK)
        run: eas build --platform android --profile preview --local false
