name: Build APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Fix Assets (عشان ننهي أزمة الصور)
        run: |
          mkdir -p assets
          # بننشئ ملفات وهمية لو مش موجودة عشان الـ prebuild ميزعلش
          touch assets/icon.png
          touch assets/adaptive-icon.png
          touch assets/favicon.png

      - name: Prebuild Expo Application
        run: npx expo prebuild --platform android

      - name: Build Android Preview (APK)
        run: |
          cd android && ./gradlew assembleDebug
